server:
  port: 8081

spring:
  datasource:
    username: root
    password: letmeinpls
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring-jwt-auth?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
