server:
  port: 8081

spring:
  datasource:
    username: root
    password: letmeinpls
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring-jwt-auth?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#rsa:
#  private-key: classpath:certs/private.pem
#  public-key: classpath:certs/public.pem

# to generate asymmetric keys
#   for keypair.pem
#     openssl genrsa -out keypair.pem 2048
#   for public.pem
#     openssl rsa -in keypair.pem -pubout -out public.pem
#   for private.pem
#     openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in keypair.pem -out private.pem


